# Generated by Django 5.2.8 on 2026-01-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_olympus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
