# Generated by Django 5.2.8 on 2026-01-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_olympus', '0002_plan_is_premium_alter_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
