# Generated by Django 5.2.8 on 2026-01-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_olympus', '0003_profile_deleted_at_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deleted_at',
        ),
    ]
