# Generated by Django 5.2.8 on 2026-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_olympus', '0006_invitation_profile_bank_account_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
