# Generated by Django 5.2.8 on 2026-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_olympus', '0007_invitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
